version: "3.9"

services:
  backend:
    container_name: desKI-backend
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/app
      - chroma_data:/app/chroma_data
    ports:
      - "8000:8000"
    command: sleep infinity  
    user: root
    environment:
      - PYTHONUNBUFFERED=1
    

volumes:
  chroma_data:
