version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - chroma_data:/app/chroma_data
    command: sleep infinity
    user: vscode

volumes:
  chroma_data:
