version: "3.9"

services:
  backend:
    container_name: deski-backend
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../digdir-camp-2025-desKI:/app
      - chroma_data:/app/chroma_data
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    user: root
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
volumes:
  chroma_data:
  