

services:
  backend:
    build:
      context: ../../.. 
      dockerfile: .devcontainer/Dockerfile
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    container_name: chatbot-api
    volumes:
      - ../../../:/app  # Mount prosjektroten
      - chroma_data:/app/chroma_data  # Volum for ChromaDB
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - dev

volumes:
  chroma_data:

networks:
  dev:
    driver: bridge

