name: Verify

on:
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  backend-verify:
    name: Verify Backend
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run Ruff (lint)
        run: ruff check .

      - name: Run Ruff (format check)
        run: ruff format --check .

  docker-build:
    name: Build Backend Docker Image
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker compose -f docker-compose.yml build backend

      - name: Start container (test Uvicorn)
        run: |
          docker compose -f docker-compose.yml up backend -d
          sleep 5
          docker ps
          docker logs chatbot-api || true

      - name: Shut down
        run: docker compose -f docker-compose.yml down
